/**
 * @jrmc/adonis-attachment
 *
 * @license MIT
 * @copyright Jeremy Chaufourier <jeremy@chaufourier.fr>
 */

import type { VariantConversionInput, VariantConversionOutput } from '../variants/variant_converter.js'

export type SharpBackground =
  | string
  | {
      r: number
      g: number
      b: number
      alpha: number
    }

/** Matches the resize options supported by Sharp and exposed by v5. */
export type SharpResizeOptions = {
  width?: number
  height?: number
  fit?: string
  position?: string
  background?: SharpBackground
  kernel?: string
  withoutEnlargement?: boolean
  withoutReduction?: boolean
  fastShrinkOnLoad?: boolean
}

export type SharpOutputFormat =
  | 'jpeg'
  | 'jpg'
  | 'png'
  | 'gif'
  | 'webp'
  | 'avif'
  | 'heif'
  | 'tiff'
  | 'raw'

type JpegFormatOptions = {
  quality?: number
  progressive?: boolean
  chromaSubsampling?: string
  optimiseCoding?: boolean
  optimizeCoding?: boolean
  mozjpeg?: boolean
  trellisQuantisation?: boolean
  overshootDeringing?: boolean
  optimiseScans?: boolean
  optimizeScans?: boolean
  quantisationTable?: number
  quantizationTable?: number
  force?: boolean
}

type PngFormatOptions = {
  quality?: number
  progressive?: boolean
  compressionLevel?: number
  adaptiveFiltering?: boolean
  palette?: boolean
  effort?: number
  colours?: number
  colors?: number
  dither?: number
  force?: boolean
}

type GifFormatOptions = {
  reuse?: boolean
  progressive?: boolean
  colours?: number
  colors?: number
  effort?: number
  dither?: number
  interFrameMaxError?: number
  interPaletteMaxError?: number
  loop?: number
  delay?: number | number[]
  force?: boolean
}

type WebpFormatOptions = {
  quality?: number
  alphaQuality?: number
  lossless?: boolean
  nearLossless?: boolean
  smartSubsample?: boolean
  preset?: string
  effort?: number
  loop?: number
  delay?: number | number[]
  minSize?: boolean
  mixed?: boolean
  force?: boolean
}

type AvifFormatOptions = {
  quality?: number
  lossless?: boolean
  effort?: number
  chromaSubsampling?: string
  bitdepth?: number
}

type HeifFormatOptions = {
  compression?: string
  quality?: number
  lossless?: boolean
  effort?: number
  chromaSubsampling?: string
  bitdepth?: number
}

export type SharpFormatOptions =
  | JpegFormatOptions
  | PngFormatOptions
  | GifFormatOptions
  | WebpFormatOptions
  | AvifFormatOptions
  | HeifFormatOptions

/** A v5-compatible Sharp output format declaration. */
export type SharpFormat =
  | SharpOutputFormat
  | { format: 'jpeg' | 'jpg'; options?: JpegFormatOptions }
  | { format: 'png'; options?: PngFormatOptions }
  | { format: 'gif'; options?: GifFormatOptions }
  | { format: 'webp'; options?: WebpFormatOptions }
  | { format: 'avif'; options?: AvifFormatOptions }
  | { format: 'heif'; options?: HeifFormatOptions }
  | { format: 'tiff' | 'raw' }

/** Options declared next to a converter in `config/attachment.ts`. */
export type ConverterOptions = {
  resize?: number | SharpResizeOptions
  format?: SharpFormat
  autoOrient?: boolean
  startTime?: number
  startPage?: number
  folder?: string
  [key: string]: unknown
}

export type ConverterAttributes<Options extends ConverterOptions = ConverterOptions> = VariantConversionInput & {
  options: Readonly<Options>
}

/**
 * Base class for application converters generated by `make:converter`.
 * Instances receive their configuration entry through the constructor.
 */
export default abstract class Converter<Options extends ConverterOptions = ConverterOptions> {
  readonly options: Readonly<Options>

  constructor(options: Options = {} as Options) {
    this.options = options
  }

  abstract handle(attributes: ConverterAttributes<Options>): Promise<VariantConversionOutput | undefined>
}

export function normalizeSharpFormat(format: SharpFormat): {
  format: Exclude<SharpOutputFormat, 'jpg'>
  options?: SharpFormatOptions
} {
  const declared = typeof format === 'string' ? { format } : format

  return {
    format: declared.format === 'jpg' ? 'jpeg' : declared.format,
    ...('options' in declared && declared.options ? { options: declared.options } : {}),
  }
}
