/**
 * @jrmc/adonis-attachment
 *
 * @license MIT
 * @copyright Jeremy Chaufourier <jeremy@chaufourier.fr>
 */

import type { VariantConversionInput, VariantConversionOutput } from '../variants/variant_converter.js'

/** Options declared next to a converter in `config/attachment.ts`. */
export type ConverterOptions = Record<string, unknown>

export type ConverterAttributes = VariantConversionInput & {
  options: Readonly<ConverterOptions>
}

/**
 * Base class for application converters generated by `make:converter`.
 * Instances receive their configuration entry through the constructor.
 */
export default abstract class Converter {
  readonly options: Readonly<ConverterOptions>

  constructor(options: ConverterOptions = {}) {
    this.options = options
  }

  abstract handle(attributes: ConverterAttributes): Promise<VariantConversionOutput | undefined>
}
