name: Test

on:
  push:
    branches:
      - 'feature/test-fix'

env:
  success: ✅
  failure: 🔴
  cancelled: ❌
  skipped: ⭕
  node_version: 20
  true: ✅
  false: 🔴

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04
    steps:
      - name: Update packages
        run: sudo apt-get update

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node_version }}
          registry-url: https://registry.npmjs.org/
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Remove old tmp
        run: rm -rf tests/tmp

      # - name: Create tmp dir
      #   run: mkdir tests/tmp

      # - name: Fix database directory permissions
      #   run: chmod -R u+rw tests/tmp

      - name: Run tests
        run: npm test
